### PR TITLE
152919274 Ft add fitbit support

### PR DESCRIPTION
**Pull request by inno-asiimwe**
#### What does this PR do?
Adds support to import data from fitbit.
#### Description of Task to be completed?
1. Signup for a fitbit account for the wger app.
2. Add Functionality to authenticate wger user against fitbit.
3. Add functionality to import weight data from fitbit into wger.
4. Add an import from fitbit button in the frontend.
#### What are the relevant pivotal tracker stories?
152919274

### CODE REVIEW

**Review by Awinja-j — CHANGES_REQUESTED** [review]
CLIENT_ID = '22CFSD'
 +    CLIENT_SECRET = 'e59051dd78a808c292efdcc2dff50dbb'
 +    SCOPE = 'weight'
 +    REDIRECT_URI = 'http://localhost:8000/en/fitbit/fetch'
 +
 +    # Authorization and authentication URIs
 +    AUTHORIZE_URI = 'https://www.fitbit.com/oauth2/authorize'
 +    TOKEN_REQUEST_URI = 'https://api.fitbit.com/oauth2/token'

work with @Chris-Maina to have all these in the environment variables

**Review by Awinja-j — CHANGES_REQUESTED** [review]
'Authorization': 'Basic MjJDRlNEOmU1OTA1MWRkNzhhODA4YzI5MmVmZGNjMmRmZjUwZGJi',

This as well

**Review by Awinja-j — CHANGES_REQUESTED** [review]
url = 'https://api.fitbit.com/1/user/-/body/weight/date/today/30d.json'
 +
this

**Review by Awinja-j — CHANGES_REQUESTED** [review]
```
  - export CLIENT_ID='22CFSD'
 +  - export CLIENT_SECRET='e59051dd78a808c292efdcc2dff50dbb'
 +  - export SCOPE='weight'
 +  - export REDIRECT_URI='http://localhost:8000/en/fitbit/fetch'
 +  - export AUTHORIZE_URI='https://www.fitbit.com/oauth2/authorize'
 +  - export TOKEN_REQUEST_URI='https://api.fitbit.com/oauth2/token'
 +  - export Authorization='Basic MjJDRlNEOmU1OTA1MWRkNzhhODA4YzI5MmVmZGNjMmRmZjUwZGJi',
 +  - export url='https://api.fitbit.com/1/user/-/body/weight/date/today/30d.json'
```

Nope!this is not how its done!

**Comment by inno-asiimwe** [comment]
@Awinja-Andela , All changes were made please review.

**Pull request merged**
